### ISSUE TITLE
Unmanage cluster fails if triggered immediately after import

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/monitoring-integration#351]
error Failure in Job 1f219796-cc1b-434f-92e9-0a55ab43f7ee Flow tendrl.flows.UnmanageCluster with error: Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 208, in process_job the_flow.run() File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/unmanage_cluster/__init__.py", line 82, in run raise ex AtomExecutionFailedError: Atom Execution failed. Error: Error executing atom: tendrl.objects.Cluster.atoms.DeleteMonitoringDetails on flow: Unmanage a Gluster Cluster 02 Mar 2018 12:27:31
error Failed atom: tendrl.objects.Cluster.atoms.DeleteMonitoringDetails on flow: Unmanage a Gluster Cluster 02 Mar 2018 12:27:30
info Clear monitoring data not yet complete. Timing out. (2f278f0b-d09c-4414-a5b8-1cae2eee10ff)

**Comment by nthomas-redhat** [comment]
Closing the issue as it is fixed
