### ISSUE TITLE
tendrl-monitoring-integration service fails to start with HTTPS is enabled

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/monitoring-integration#591]
Service tendrl-monitoring-integration fails to start with following traceback
  in logs:
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # systemctl status tendrl-monitoring-integration -l
  ● tendrl-monitoring-integration.service - Monitoring Integration
     Loaded: loaded (/usr/lib/systemd/system/tendrl-monitoring-integration.service; enabled; vendor preset: disabled)
     Active: failed (Result: start-limit) since Wed 2019-02-20 10:32:37 CET; 19s ago
    Process: 16594 ExecStart=/usr/bin/tendrl-monitoring-integration (code=exited, status=1/FAILURE)
   Main PID: 16594 (code=exited, status=1/FAILURE)

  Feb 20 10:32:36 tendrl-server systemd[1]: tendrl-monitoring-integration.service: main process exited, code=exited, status=1/FAILURE
  Feb 20 10:32:36 tendrl-server systemd[1]: Unit tendrl-monitoring-integration.service entered failed state.
  Feb 20 10:32:36 tendrl-server systemd[1]: tendrl-monitoring-integration.service failed.
  Feb 20 10:32:37 tendrl-server systemd[1]: tendrl-monitoring-integration.service holdoff time over, scheduling restart.
  Feb 20 10:32:37 tendrl-server systemd[1]: Stopped Monitoring Integration.
  Feb 20 10:32:37 tendrl-server systemd[1]: start request repeated too quickly for tendrl-monitoring-integration.service
  Feb 20 10:32:37 tendrl-server systemd[1]: Failed to start Monitoring Integration.
  Feb 20 10:32:37 tendrl-server systemd[1]: Unit tendrl-monitoring-integration.service entered failed state.
  Feb 20 10:32:37 tendrl-server systemd[1]: tendrl-monitoring-integration.service failed.
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # tail -F /var/log/messages | grep tendrl 
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: Traceback (most recent call last):
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: File "/usr/bin/tendrl-monitoring-integration", line 11, in <module>
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: load_entry_point('tendrl-monitoring-integration==1.6.3', 'console_scripts', 'tendrl-monitoring-integration')()
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: File "/usr/lib/python2.7/site-packages/tendrl/monitoring_integration/manager/__init__.py", line 70, in main
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: monitoring_integration_manager.start()
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: File "/usr/lib/python2.7/site-packages/tendrl/monitoring_integration/manager/__init__.py", line 31, in start
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: dashboard.upload_default_dashboards()
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: File "/usr/lib/python2.7/site-packages/tendrl/monitoring_integration/grafana/dashboard.py", line 17, in upload_default_dashboards
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: main_org_id = grafana_org_utils.get_org_id(constants.MAIN_ORG)
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: File "/usr/lib/python2.7/site-packages/tendrl/monitoring_integration/grafana/grafana_org_utils.py", line 42, in get_org_id
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: auth=config.credentials
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: File "/usr/lib/python2.7/site-packages/requests/api.py", line 68, in get
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: return request('get', url, **kwargs)
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: response = session.request(method=method, url=url, **kwargs)
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: resp = self.send(prep, **send_kwargs)
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 602, in send
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: history = [resp for resp in gen] if allow_redirects else []
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 195, in resolve_redirects
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: allow_redirects=False,
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: r = adapter.send(request, **kwargs)
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: raise SSLError(e, request=request)
  Feb 20 10:32:36 tendrl-server tendrl-monitoring-integration: requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)
  Feb 20 10:32:36 tendrl-server systemd: tendrl-monitoring-integration.service: main process exited, code=exited, status=1/FAILURE
  Feb 20 10:32:36 tendrl-server systemd: Unit tendrl-monitoring-integration.service entered failed state.
  Feb 20 10:32:36 tendrl-server systemd: tendrl-monitoring-integration.service failed.
  Feb 20 10:32:37 tendrl-server systemd: tendrl-monitoring-integration.service holdoff time over, scheduling restart.
  Feb 20 10:32:37 tendrl-server systemd: start request repeated too quickly for tendrl-monitoring-integration.service
  Feb 20 10:32:37 tendrl-server systemd: Unit tendrl-monitoring-integration.service entered failed state.
  Feb 20 10:32:37 tendrl-server systemd: tendrl-monitoring-integration.service failed.
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  For the full log see the attached log.

**Comment by GowthamShanmugam** [comment]
This issue is fixed
